version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - commerce-api
    restart: always

  nestjs:
    container_name: nestjs
    build: .
    env_file:
      - .env
    ports:
      - "${PORT}:5000"
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - postgres
    networks:
      - commerce-api
    restart: always
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nestjs

networks:
  commerce-api:
    driver: bridge
