version: "3"
services:
  postgres:
    container_name: commerce-api
    image: postgres:latest
    ports:
    - "${POSTGRES_PORT}:5432"
    volumes:
    - ./data:/data/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
    - postgres
    restart: always

networks:
  postgres:
    driver: bridge