version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./data:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - commerce-api
    restart: always

  nestjs:
    container_name: nestjs
    build: .
    env_file:
      - .env
    ports:
      - "5000"
    depends_on:
      - postgres
    networks:
      - commerce-api
    restart: always

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - "${NGINX_PORT}:443"
    depends_on:
      - nestjs
    networks:
      - commerce-api
    restart: always

networks:
  commerce-api:
    driver: bridge
